#pragma once
#define ACTION_DELETE 'S'
#define ACTION_CTRL_DELETE -109
#define ACTION_LEFT_KEY 'K'
#define ACTION_RIGHT_KEY 'M'
#define ACTION_UP_KEY 'H'
#define ACTION_DOWN_KEY 'P'
#define ACTION_CTRL_RIGHT_KEY 't'
#define ACTION_CTRL_LEFT_KEY 's'
#define ACTION_ALT_UP 152
#define ACTION_ALT_DOWN 160
#define ACTION_CTRL_S 19
#define ACTION_CTRL_D 4
#define ACTION_CTRL_L 12
#define ACTION_ENTER '\r'
#define ACTION_CTRL_ENTER '\n'
#define ACTION_REMOVE 8
#define ACTION_CTRL_REMOVE 127
#define ACTION_FN_RIGHT 79
#define ACTION_FN_LEFT 71
#define ACTION_START_COMMAND 3
#define ACTION_TABIFY 29
#define ACTION_UNTABIFY 27

#define NEXT_IS_UTILS -32

#define BEGIN_CALLED_COMMAND ':'

#define COMMAND_SAVE "s"
#define COMMAND_OPEN "o"
#define COMMAND_QUIT "Q"
#define COMMAND_QUIT_AND_SAVE "q"
#define COMMAND_PASTE "p"
#define COMMAND_DELETE_WORD "dw"
#define COMMAND_DELETE_LINE "dl"
#define COMMAND_REMOVE_WORD "db"
#define COMMAND_MOVE_WORD "w"
#define COMMAND_BACK_WORD "b"
#define COMMAND_TABIFY "ta"
#define COMMAND_UNTABIFY "ut"
#define COMMAND_LEFT_KEY "h"
#define COMMAND_RIGHT_KEY "l"
#define COMMAND_UP_KEY "k"
#define COMMAND_DOWN_KEY "j"
#define COMMAND_COPY_WORD "cw"
#define COMMAND_COPY_LINE "cl"
#define COMMAND_COPY_WORD_BACK "cb"


#define EXIT_CMD_MODE 'i'